wandb_version: 1

epochs:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.007847632038505128
momentum:
  desc: null
  value: 0.997750340032062
test_percent:
  desc: null
  value: 0.1198544226550994
validation_percent:
  desc: null
  value: 0.10187964597144032
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704928571.846619
    t:
      1:
      - 1
      - 41
      - 55
      - 105
      2:
      - 1
      - 41
      - 55
      - 105
      3:
      - 2
      - 5
      - 23
      4: 3.11.5
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
batch_size:
  desc: null
  value: 4
save_checkpoint:
  desc: null
  value: false
