wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704922963.05113
    t:
      1:
      - 1
      - 41
      - 55
      - 105
      2:
      - 1
      - 41
      - 55
      - 105
      3:
      - 23
      4: 3.11.5
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
epochs:
  desc: null
  value: 2
batch_size:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 0.002
test_percent:
  desc: null
  value: 0.1
validation_percent:
  desc: null
  value: 0.2
save_checkpoint:
  desc: null
  value: false
