wandb_version: 1

epochs:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.004338892135643516
momentum:
  desc: null
  value: 0.989366265335222
test_percent:
  desc: null
  value: 0.17702397247852747
validation_percent:
  desc: null
  value: 0.159538230372749
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704928306.108659
    t:
      1:
      - 1
      - 41
      - 55
      - 105
      2:
      - 1
      - 41
      - 55
      - 105
      3:
      - 2
      - 5
      - 23
      4: 3.11.5
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
